version: '3'

services:
    nginx-proxy:
        image: project/njinx-proxy
        build: ./nginx/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
            - "3306:3306"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - default

networks:
   default:
      ipam:
         config:
            - subnet: 172.16.0.0/24
